"""create roles

Revision ID: 783f20ab6af8
Revises: d0e84d97118d
Create Date: 2026-03-04 22:19:17.605246

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision: str = '783f20ab6af8'
down_revision: Union[str, Sequence[str], None] = 'd0e84d97118d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # create default roles
    roles_table = sa.table(
        "roles",
        sa.column("uuid", sa.String),
        sa.column("name", sa.String),
    )

    admin_role_uuid = str(uuid.uuid4())
    user_role_uuid = str(uuid.uuid4())

    op.bulk_insert(
        roles_table,
        [
            {"uuid": admin_role_uuid, "name": "admin"},
            {"uuid": user_role_uuid, "name": "user"}
        ],
    )

    # create first admin
    users_table = sa.table(
        "users",
        sa.column("uuid", sa.String),
        sa.column("email", sa.String),
        sa.column("password", sa.String),
    )

    user_uuid = str(uuid.uuid4())

    op.bulk_insert(
        users_table,
        [
            {"uuid": user_uuid, "email": "admin@treasury.com", "password": generate_password_hash("pass1234")}
        ],
    )

    # fill user_roles table
    ur_table = sa.table(
        "user_roles",
        sa.column("user_id", sa.String),
        sa.column("role_id", sa.String),
    )

    op.bulk_insert(
        ur_table,
        [
            {"user_id": user_uuid, "role_id": admin_role_uuid},
            {"user_id": user_uuid, "role_id": user_role_uuid}
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_roles")
    op.execute("DELETE FROM roles")
    op.execute("DELETE FROM users")
    # ### end Alembic commands ###
