"""create tables

Revision ID: b7eb8cc52b80
Revises: 
Create Date: 2026-03-18 21:46:30.072995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7eb8cc52b80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=164), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('budgets',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('month', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_budgets_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_budgets'))
    )
    op.create_index(op.f('ix_budgets_uuid'), 'budgets', ['uuid'], unique=False)
    op.create_table('categories',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_categories_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_uuid'), 'categories', ['uuid'], unique=False)
    op.create_table('expenses',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_expenses_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_uuid'), 'expenses', ['uuid'], unique=False)
    op.create_table('incomes',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_incomes_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_incomes'))
    )
    op.create_index(op.f('ix_incomes_uuid'), 'incomes', ['uuid'], unique=False)
    op.create_table('receipts',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('original_name', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_receipts_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_receipts'))
    )
    op.create_index(op.f('ix_receipts_uuid'), 'receipts', ['uuid'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.uuid'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_user_roles_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_receipts_uuid'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_incomes_uuid'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_expenses_uuid'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_categories_uuid'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_budgets_uuid'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
