"""initial migration

Revision ID: d0e84d97118d
Revises: 
Create Date: 2026-03-04 22:02:27.695448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e84d97118d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
